name: caoital55
description: تطبيق العاصمة للبيع والشراء
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - إصدارات متوافقة
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  
  # تسجيل الدخول الاجتماعي
  google_sign_in: ^6.1.6
  # Apple Sign-In (تم التعليق مؤقتًا)
  # sign_in_with_apple: ^5.0.0
  
  # UI & Images
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0 # ✅ محدث لدعم أيقونة X (Twitter)
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  
  # الأمان
  crypto: ^3.0.3
  
  # بوابة الدفع - جيديا
  webview_flutter: ^4.4.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # لتوليد أيقونة التطبيق
  flutter_launcher_icons: ^0.13.1
  # لتوليد شاشة البداية
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
  
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: fonts/Cairo-Regular.ttf
  #       - asset: fonts/Cairo-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/banner1.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/banner1.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/banner1.jpg
  android: true
  ios: true
